Version 1.0 Create new branch - controllers-films-users
Asteises/java-filmorate pull request #1
Opened 2022-06-02 08:10 UTC by Asteises

Первая версия проекта. Просьба проверить.

2022-06-03 13:43 UTC, alexache requested changes
Нужно бы добавить тестов, логов, и сделать чтобы тесты постмана проходили

2022-06-03 13:43 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    }
Не помешает больше тестов, на валидацию разных полей, а не всех разом

2022-06-03 13:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @DateAfter
Где валидация даты релизы после указанной в ТЗ даты?

2022-06-03 13:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().equals("")) {
Из-за того, что часть изменений уже в мастер ветке, я не могу их ревьюить, так лучше не делать.
Второе - хранение в листе не оптимально, ведь есть кейс получения юзера по айди, то есть какая структура данных тут лучше подойдет?

2022-06-03 13:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          users.add(user);
Не хватает логгирования, как описано в ТЗ - на добавление или изменение сущностей

2022-06-03 13:43 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
>          Assertions.assertTrue(violations.stream().anyMatch(v -> v.getMessage().equals("должно быть не меньше 1")));
Не помешает больше тестов на разные граничные условия по отдельности

2022-06-05 15:39 UTC, Asteises commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    }
Исправлено

2022-06-05 15:39 UTC, Asteises commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @DateAfter
Исправлено

2022-06-05 15:40 UTC, Asteises commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().equals("")) {
Исправлено

2022-06-05 15:40 UTC, Asteises commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          users.add(user);
Исправлено

2022-06-05 15:40 UTC, Asteises commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
>          Assertions.assertTrue(violations.stream().anyMatch(v -> v.getMessage().equals("должно быть не меньше 1")));
Исправлено

2022-06-05 19:46 UTC, alexache approved these changes
Оставил немного некритичных комментариев

2022-06-05 19:46 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> films;
(можно лучше) поле может быть final

2022-06-05 19:46 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Map<Integer, User> users;
(можно лучше) поле может быть final

2022-06-05 19:46 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/utils/DateValidator.java
>      public boolean isValid(LocalDate localDate, ConstraintValidatorContext constraintValidatorContext) {
Понял, теперь этот класс виден с PR, в мастере не искал

2022-06-05 19:46 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    public void validateFilmNameTest() {
(можно лучше) я бы еще добавил пару тестов - пустой объект фильма (null) и другие вариации некорректного фильма

2022-06-16 15:43 UTC, merged